using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Tungsten.Api.Features.FormSd.Templates;

public class FormSdPackageTemplate(FormSdPackageData data) : IDocument
{
    public DocumentMetadata GetMetadata() => new()
    {
        Title = $"Form SD Support Package — {data.TenantName} — {data.ReportingYear}",
        Author = "auditraks",
    };

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);
            page.DefaultTextStyle(x => x.FontSize(10));

            page.Header().Column(col =>
            {
                col.Item().Text($"FORM SD SUPPORT PACKAGE").Bold().FontSize(16);
                col.Item().Text($"{data.TenantName} — Reporting Year {data.ReportingYear}").FontSize(12).FontColor(Colors.Grey.Darken1);
                col.Item().PaddingTop(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.RelativeItem().Text($"Generated by: {data.GeneratedBy}").FontSize(8);
                    row.RelativeItem().AlignRight().Text($"Rule Set: {data.RuleSetVersion} | Platform: {data.PlatformVersion}").FontSize(8);
                });
                col.Item().PaddingBottom(10);
            });

            page.Content().Column(col =>
            {
                // Section 1: Applicability
                col.Item().Text("1. 3TG APPLICABILITY DETERMINATION").Bold().FontSize(13);
                col.Item().PaddingTop(5);
                foreach (var a in data.Applicability)
                    col.Item().Row(row =>
                    {
                        row.ConstantItem(120).Text(a.BatchNumber).SemiBold();
                        row.ConstantItem(100).Text(a.MineralType);
                        row.ConstantItem(50).Text(a.OriginCountry);
                        row.RelativeItem().Text(a.Status).Bold()
                            .FontColor(a.Status == "IN_SCOPE" ? Colors.Orange.Darken2 : a.Status == "OUT_OF_SCOPE" ? Colors.Green.Darken2 : Colors.Red.Darken2);
                    });

                col.Item().PaddingVertical(15).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                // Section 2: Supply Chain
                col.Item().Text("2. SUPPLY CHAIN DESCRIPTIONS").Bold().FontSize(13);
                col.Item().PaddingTop(5);
                foreach (var sc in data.SupplyChains)
                    col.Item().PaddingBottom(5).Column(inner =>
                    {
                        inner.Item().Text($"{sc.BatchNumber} ({sc.EventCount} events, {sc.GapCount} gaps)").SemiBold();
                        inner.Item().Text(sc.NarrativeText).FontSize(9);
                    });

                col.Item().PaddingVertical(15).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                // Section 3: Due Diligence
                col.Item().Text("3. DUE DILIGENCE PROCESS DOCUMENTATION").Bold().FontSize(13);
                col.Item().PaddingTop(5);
                foreach (var dd in data.DueDiligence)
                    col.Item().PaddingBottom(5).Column(inner =>
                    {
                        inner.Item().Text($"{dd.BatchNumber} — {dd.FlagCount} flag(s), OECD DDG {dd.OecdVersion}").SemiBold();
                        inner.Item().Text(dd.SummaryText).FontSize(9);
                        if (dd.SmelterNames.Count > 0)
                            inner.Item().Text($"Smelters: {string.Join(", ", dd.SmelterNames)}").FontSize(9).Italic();
                    });

                col.Item().PaddingVertical(15).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                // Section 4: Risk Assessment
                col.Item().Text("4. RISK ASSESSMENT SUMMARY").Bold().FontSize(13);
                col.Item().PaddingTop(5);
                foreach (var ra in data.RiskAssessments)
                    col.Item().PaddingBottom(5).Column(inner =>
                    {
                        inner.Item().Text($"{ra.BatchNumber} — Overall: {ra.OverallRating}").SemiBold()
                            .FontColor(ra.OverallRating == "HIGH" ? Colors.Red.Darken2 : ra.OverallRating == "MEDIUM" ? Colors.Orange.Darken2 : Colors.Green.Darken2);
                        foreach (var cat in ra.Categories)
                            inner.Item().Text($"  {cat.Category}: {cat.Rating} — {cat.Detail}").FontSize(9);
                    });
            });

            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Page "); x.CurrentPageNumber(); x.Span(" of "); x.TotalPages();
                x.Span($" — Generated {data.GeneratedAt:yyyy-MM-dd HH:mm} UTC");
            });
        });
    }
}
